services:
  backend-to-api:
    image: gptenv/refresh-to-v1-api:latest
    restart: always
    ports:
      - "50011:33333"
    volumes:
      - ./log:/app/log
      - ./images:/app/images
      - ./data:/app/data
      - ./files:/app/files
    env_file:
      - ./.env
      
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data

